spring.application.name=petclinic-api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
